# dns.tf — DNS record declarations for zambone.dev
#
# Each cloudflare_dns_record resource manages one DNS record in the zone.
# When proxied = true, Cloudflare returns its own proxy IPs instead of the
# origin — this is what enables WAF, DDoS protection, and caching.

# CNAME record: pfm-go-api.zambone.dev → pfm-go-api.fly.dev
#
# This routes API traffic through Cloudflare's proxy before it reaches
# the Fly.io origin. The "proxied = true" flag is critical — without it,
# DNS would resolve directly to Fly.io, bypassing all Cloudflare protections.
#
# TTL is set to 1 (automatic) because proxied records don't use traditional
# TTL — Cloudflare controls the cache behavior at the proxy layer.
resource "cloudflare_dns_record" "pfm_api_cname" {
  zone_id = var.cloudflare_zone_id
  name    = "pfm-go-api"
  type    = "CNAME"
  content = var.fly_app_hostname
  proxied = true
  ttl     = 1
}

# ACME DNS challenge record for Fly.io Let's Encrypt cert provisioning.
#
# Fly.io uses DNS-based ACME challenges to issue TLS certs for custom domains.
# This CNAME delegates the challenge response to Fly.io's DNS infrastructure
# (flydns.net), so Fly.io can automatically prove domain ownership to Let's
# Encrypt without needing to serve HTTP challenges through our proxy.
#
# Must NOT be proxied — ACME validation resolves DNS directly, and a proxied
# record would return Cloudflare IPs instead of the ACME response.
#
# The "9l61kwy" segment is Fly.io's internal app identifier for pfm-go-api.
resource "cloudflare_dns_record" "pfm_api_acme_challenge" {
  zone_id = var.cloudflare_zone_id
  name    = "_acme-challenge.pfm-go-api"
  type    = "CNAME"
  content = "pfm-go-api.zambone.dev.9l61kwy.flydns.net"
  proxied = false
  ttl     = 300
}

# Fly.io ownership verification TXT record.
#
# Required because traffic to pfm-go-api.zambone.dev is routed through
# Cloudflare's proxy — Fly.io can't verify ownership by checking that our
# DNS points to their IPs. This TXT record provides an alternative proof
# that we control the domain and authorize Fly.io to serve it.
#
# The "app-9l61kwy" value is generated by Fly.io and tied to the pfm-go-api app.
resource "cloudflare_dns_record" "pfm_api_fly_ownership" {
  zone_id = var.cloudflare_zone_id
  name    = "_fly-ownership.pfm-go-api"
  type    = "TXT"
  content = "app-9l61kwy"
  proxied = false
  ttl     = 300
}
